feat: run tests and save progress in API
Laboratoria/prework-topic-submit pull request #1
Opened 2021-06-30 15:44 UTC by Danielalab

Hola @merunga ! Te compartimos las funcionalidades que estuvimos avanzando, nos gustaría ir recibiendo feedback. 
- Se autentica al usuario enviando un request a API `/auth` para obtener el token. Por ahora el request se envía a **API Staging**.
- Al correr los tests se obtiene un objeto con la siguiente información sobre los tests ejecutados:
``` js
 {
    state: null, // string: 'PASS' OR 'FAIL'
    stats: {
      suites: 0, // number
      tests: 0, // number
      passes: 0, // number
      pending: 0, // number
      failures: 0, // number
      start: null, // Date
      end: null, // Date
      duration: 0, // number
    },
  };

```
- Para guardar el progreso este sería el formato de nuestro body request.
``` js
{
  "unitId": "04-prework",
  "partId": "17-js-basics",
  "exerciseId": "01-comments",
  "type": "practice",
  "progress": {
    "testResults": {
      "state": "FAIL",
      "stats": {
        "suites": 1,
        "tests": 3,
        "passes": 0,
        "pending": 0,
        "failures": 2,
        "start": "2021-06-23T17:51:43.377Z",
        "end": "2021-06-23T17:51:46.711Z",
        "duration": 1
      }
    },
    "updatedAt": "2021-06-23T17:51:46.711Z",
    /* Add completedAt property only if tests passed to save in BigQuery */
    "completedAt": "2021-06-23T17:51:46.711Z"
  }
}
```
- Separamos la funcionalidad del spinner para para poder reutilizarla al correr los tests y al guardar el progreso.

rel [admission-curriculum #69](https://github.com/Laboratoria/admission-curriculum/issues/69)

2021-07-14 13:41 UTC, merunga requested changes
@Danielalab buenisimos los tests, encontre algo raro en los tests de main.
Si necesitas ayuda para identificar el problema me avisas y lo vemos.

2021-07-14 13:41 UTC, merunga commented on index.js
> +  return runTests()
@Danielalab creo q es necesario invertir el orden de las acciones de correr los tests y pedir las credenciales. Por qué? porque si por ejemplo pones una contraseña incorrecta, los tests se corren en vano y pierdes tiempo de espera.
Entonces, creo q primero deberiamos pedir las credenciales y obtener el token, y luego correr los tests, para que la experiencia del usuario sea mas amigable

2021-07-14 13:41 UTC, merunga commented on index.js
> +      console.log(kleur.bold().italic('Se terminó de correr los tests. A continuación completa los siguientes datos:'));
Aquí, por un tema de transparencia, deberíamos mostrar el resultado de los tests, para q no sea una sorpresa o tengas q ir a la app para saber q paso

2021-07-14 13:41 UTC, merunga commented on api-service.js
> +const sendProgressToApi = (data, token) => fetch('https://laboratoria-la-staging.web.app/dashboards/redesign-prework-fe', {
lo mismo q con la URL de autenticacion

2021-07-14 13:41 UTC, merunga commented on api-service.js
> +    return 'Listo! Tu progreso ha sido guardado de forma exitosa.';
Aqui, nuevamente, necesitamos dar feedback al usuario sobre qué efecto tuvo este submit en su progeso

2021-07-14 13:41 UTC, merunga commented on api-service.js
> +  return fetch('https://laboratoria-la-staging.web.app/auth', {
esta url de la API deberia estar abstraida a una variable de entorno y si la variable no esta definida, deberia hacer un fallback a un valor por defecto

2021-07-14 13:41 UTC, merunga commented on index.js
> +  .then((successMessage) => console.log(kleur.green().bold(successMessage)))
@Danielalab cuando corro los tests obtengo un `Cannot read property 'then' of undefined` proveniente de la linea 60.
Creo q hay algo en el mock de `prompts` q no esta funcionando como se espera.

Para aislar el problema puedes poner un `fit` a cualquiera de los siguientes tests de `index.spec.js/main`
- should be return an error message with wrong email & password
- skipped should be return a success message

Para ejecutar solo `index.spec.js` puedes hacerlo con este comando:
`npm run test -- tests/index.spec.js`

2021-07-15 18:43 UTC, Danielalab reviewed
Hola @merunga ! Hice estas modifcaciones:
- Se agregó la variable de entorno `process.env.URL_API`.
- Se agregó la función `showTestsResults` para mostrar a la usuaria si los tests fallaron o no.
- Se cambio el orden del código para primero validar las credenciales del usuario y luego correr los tests.
- Se actualizaron los tests y algunos mocks para solucionar el error `Cannot read property 'then' of undefined`
- El archivo `index.js` fue modificado para que solo ejecute una función (`submitProgress`) y muestre un mensaje en consola.

2021-07-16 17:51 UTC, merunga requested changes
@Danielalab va quedando buenisimo, lo que todavia no he podido ver es el output final, no sesi se esta mostrando o no

![image](https://user-images.githubusercontent.com/211721/125988929-f6d19515-c6d9-438b-86f6-51d9ac0468ba.png)

2021-07-16 17:51 UTC, merunga commented on api-service.js
> +const urlAPI = process.env.URL_API || 'http://localhost:5000/auth';
el valor por defecto creo q deberia ser `http://localhost:5000` a secas, no?

2021-07-16 17:51 UTC, merunga commented on index.js
> +const submitProgress = require('./submitProgress');
este `import` creo q está mal, porque desde `submitProgress.s` estas exportando un `object`

2021-07-16 17:51 UTC, merunga commented on index.js
> +submitProgress()
como estas testeando este call? yo encontre lo de arriba ejecutandolo en un sandbox real

2021-07-16 17:51 UTC, merunga commented on submitProgress.js
> +      console.log('response', response);
esto tiene q salir. Escribe tu contraseña en limpio en la consola

2021-07-21 17:05 UTC, Danielalab commented on api-service.js
> +const urlAPI = process.env.URL_API || 'http://localhost:5000/auth';
Sip, voy a modificarlo.

2021-07-21 19:45 UTC, Danielalab commented on index.js
> +const submitProgress = require('./submitProgress');
Si, aquí me falto desestructurar el objeto. Voy a realizar el cambio.

2021-07-21 19:47 UTC, Danielalab commented on submitProgress.js
> +      console.log('response', response);
Si, este es el mensaje inicial que debe salir al correr el script.

2021-07-21 22:23 UTC, Danielalab commented
Hola @merunga !
Hice el cambio de la URL y la forma en como se importa `submitProgress`.
También tenía un bug con el request que guarda el progreso por lo que he cambiado la validación de `statusCode` a `status`.
Por otro lado el script ahora necesita que coloquemos el **`courseId`** (slug del topic) en el objeto **"laboratoria"** ya que es un campo requerido en el endpoint.
Aquí un ejemplo del nuevo formato:
``` json
  "laboratoria": {
    "courseId": "admission-redesign-fe",
    "unitId": "03-prework",
    "partId": "06-js-basics",
    "exerciseId": "02-data-types-numbers",
    "typeContent": "practice"
  },
```

Para el nuevo contenido estamos considerando como slug del topic este nombre `"admission-redesign-fe"`. Con @MaiaRojas subimos el contenido con la nueva estructura de carpetas y le asignamos este slug.
Puedes encontrar este contenido en staging con el nombre de "Proceso de selección: rediseño FE" y version "v5.0.0".

![topico](https://user-images.githubusercontent.com/32286663/126567586-8def0bb7-201c-4d4a-8602-d0620467e869.png)

Para que puedas hacer pruebas debes considerar que tu usuario este asociado a un cohort que tenga como contenido el tópico con la nueva estructura de carpetas.

2021-07-22 08:15 UTC, merunga commented on __mocks__/package.json
> +    "courseId": "admission",
@Danielalab esto es un valor fijo o varia para cada preadmission?

2021-07-22 08:45 UTC, merunga reviewed
@Danielalab usando esta version y este package.json

![image](https://user-images.githubusercontent.com/211721/126611595-802dba65-e4ab-4820-89c1-1e6415464aaa.png)

Sigo teniendo un error al hacer el submit

![image](https://user-images.githubusercontent.com/211721/126611671-166e56b9-bca3-4f49-bc28-1533073c2dd8.png)

debuggeando vi q es un error 404.

Mi pregunta es si este el path de este endpoint no deberia tb ser dinamico
https://github.com/Danielalab/prework-topic-submit/blob/feat/submit-script/api-service.js#L25

Lo q no entiendo, es el papel juega aqui `dashboards` y si `redesign-prework-fe` en realidad no es un slug q va cambiando

2021-07-22 16:07 UTC, Danielalab commented on __mocks__/package.json
> +    "courseId": "admission",
Debe ser el slug del tópico que se genera al subir el contenido a API.

2021-07-22 16:11 UTC, Danielalab commented
Hola @merunga !
Hice el cambio de la URL y la forma en como se importa `submitProgress`.
También tenía un bug con el request que guarda el progreso por lo que he cambiado la validación de `statusCode` a `status`.
Por otro lado el script ahora necesita que coloquemos el **`courseId`** (slug del topic) en el objeto **"laboratoria"** ya que es un campo requerido en el endpoint.
Aquí un ejemplo del nuevo formato:
``` json
  "laboratoria": {
    "courseId": "admission-redesign-fe",
    "unitId": "03-prework",
    "partId": "06-js-basics",
    "exerciseId": "02-data-types-numbers",
    "typeContent": "practice"
  },
```
Para el nuevo contenido estamos considerando como slug del topic este nombre `"admission-redesign-fe"`. Con @MaiaRojas subimos el contenido con la nueva estructura de carpetas y le asignamos este slug.
Esperamos mantener un slug fijo para el nuevo contenido ya que el también necesitamos condicionar como se muestra el contenido en admision.laboratoria.la.
Puedes encontrar el contenido que subimos en staging con el nombre de "Proceso de selección: rediseño FE" y version "v5.0.0".
![topico](https://user-images.githubusercontent.com/32286663/126567586-8def0bb7-201c-4d4a-8602-d0620467e869.png)
Para que puedas hacer pruebas debes considerar que tu usuario este asociado a un cohort que tenga como contenido el tópico con la nueva estructura de carpetas.

2021-08-10 19:05 UTC, merunga commented
@Danielalab lo volvi a probar, pero sigo obteniendo un error.

He creado una rama del sandbox para q tu misma lo puedas probar en un entorno integrado:
https://lab.cs50.io/Laboratoria/admission-curriculum/rediseno-prework-fe-submit/admission/03-prework/04-html-basics/01-document/

Recuerda hacer `npm install` al comenzar.

si quieres q los tests pasen, coloca lo siguiente en `src/index.html`
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Hola</title>
  </head>
  <body>
    <!-- This is a comment -->
  </body>
</html>
```

Recuerda q si realizas cambio en el repo, necesitas volver a instalar la dependencia:
```
npm remove @laboratoria/prework-topic-submit
npm install -D Danielalab/prework-topic-submit#feat/submit-script
```

2021-08-12 19:08 UTC, Danielalab commented
Hola @merunga ! realice un cambio que soluciona el error. Necesitaba agregar una propiedad que era necesaria en el endpoint.
Me cuentas como te va con esta modificación. 

![exito](https://user-images.githubusercontent.com/32286663/129254360-ccd9a76f-f8c7-4405-b62a-49d1523ab121.png)

2021-08-17 19:41 UTC, merged